import type { NornReport } from "./types";

// A simplified ClinVar germline submission row derived from a Norn report. This
// is a starting point for a curator, not a validated submission. Real
// submissions require registration, a condition, and human sign-off.
export function toClinvarSubmission(report: NornReport): Record<string, string> {
  const c = report.evidence.consequence;
  const n = report.evidence.normalized;
  const met = report.result.criteria.filter((x) => x.verdict === "met").map((x) => x.code);
  return {
    "Gene symbol": c.geneSymbol ?? "",
    "Reference sequence": c.transcriptId ?? "",
    HGVS: c.hgvsc ?? report.input,
    "Protein change": c.hgvsp ?? "",
    Chromosome: n.chrom ?? "",
    Start: n.pos != null ? String(n.pos) : "",
    "Reference allele": n.ref ?? "",
    "Alternate allele": n.alt ?? "",
    Condition: "not provided",
    "Germline classification": report.result.classification,
    "Date last evaluated": report.generatedAt.slice(0, 10),
    "Classification statement": `${report.result.classification} (${report.result.points} ClinGen points). Criteria met: ${met.length ? met.join(";") : "none"}.`,
    "Assertion method": "ACMG/AMP 2015 with ClinGen Bayesian points (Tavtigian 2018/2020)",
    "Collection method": "curation",
    "Allele origin": "germline",
    "Affected status": "unknown",
    Comment: "Draft generated by Norn (research and demonstration only). Requires human confirmation before any submission.",
  };
}

export function submissionCsv(report: NornReport): string {
  const row = toClinvarSubmission(report);
  const keys = Object.keys(row);
  const esc = (v: string) => `"${String(v).replace(/"/g, '""')}"`;
  return `${keys.map(esc).join(",")}\n${keys.map((k) => esc(row[k])).join(",")}\n`;
}
